import { MapContainer, TileLayer, LayersControl, useMap, useMapEvents } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet.heat';
import booleanPointInPolygon from '@turf/boolean-point-in-polygon';
import { point as turfPoint } from '@turf/helpers';
import { mask as turfMask } from '@turf/mask';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { fetchCrimeStatistics, fetchNeighborhoods } from '../config/api';
import { decimalFormatter, numberFormatter } from '../utils/format';

/** Baixada Santista boundary layers generated by scripts/process-baixada-santista.mjs */
const MUNICIPALITIES_GEOJSON_URL = '/baixada-santista-municipalities.geojson';
const NEIGHBORHOODS_GEOJSON_URL = '/baixada-santista-neighborhoods.geojson';

/** Zoom level at which the map switches from municipalities to neighborhoods (bairros) */
const NEIGHBORHOOD_ZOOM = 12;

const EMPTY_STATISTICS = { total: 0, by_crime_type: [], by_month: [], by_location: [] };

const { BaseLayer } = LayersControl;

const BASE_LAYER_NAMES = ['Mapa Claro', 'Mapa Escuro', 'Satélite'];

function getRiskLevel(intensity) {
  if (intensity == null)    return { label: 'Sem dados',  color: '#9aa4b2' };
  if (intensity >= 0.8)     return { label: 'Muito alto', color: '#7f0000' };
  if (intensity >= 0.6)     return { label: 'Alto',       color: '#b71c1c' };
  if (intensity >= 0.4)     return { label: 'Médio',      color: '#e53935' };
  if (intensity >= 0.2)     return { label: 'Baixo',      color: '#ef9a9a' };
  return                           { label: 'Muito baixo',color: '#ffcdd2' };
}

function getRiskColor(intensity) {
  return getRiskLevel(intensity).color;
}

function normalizeName(name) {
  return (name ?? '').trim().toLowerCase();
}

const NEIGHBORHOOD_PALETTE = ['#7c5cff', '#6f8cff', '#5f9dff', '#50adff', '#42bdf2', '#8a63d8', '#756ed9', '#6485e6'];

function escapeTooltipText(value) {
  return String(value ?? '').replace(/[&<>"']/g, (character) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  })[character]);
}

function pointOnCircle(radius, angle) {
  const radians = (angle * Math.PI) / 180;
  return [42 + Math.cos(radians) * radius, 42 + Math.sin(radians) * radius];
}

function buildNeighborhoodDonut(rows) {
  const total = rows.reduce((sum, row) => sum + row.total, 0);
  if (!rows.length || !total) {
    return '<div class="crime-tooltip-breakdown-empty">Sem ocorrências nos bairros para estes filtros</div>';
  }

  let currentAngle = -90;
  const paths = [];

  rows.forEach((row, index) => {
    const angle = (row.total / total) * 360;
    const endAngle = currentAngle + angle;
    const outerStart = pointOnCircle(38, currentAngle);
    const outerEnd = pointOnCircle(38, endAngle);
    const innerEnd = pointOnCircle(21, endAngle);
    const innerStart = pointOnCircle(21, currentAngle);
    const largeArc = angle > 180 ? 1 : 0;
    const color = NEIGHBORHOOD_PALETTE[index % NEIGHBORHOOD_PALETTE.length];
    paths.push(`<path d="M ${outerStart[0]} ${outerStart[1]} A 38 38 0 ${largeArc} 1 ${outerEnd[0]} ${outerEnd[1]} L ${innerEnd[0]} ${innerEnd[1]} A 21 21 0 ${largeArc} 0 ${innerStart[0]} ${innerStart[1]} Z" fill="${color}"/>`);
    currentAngle = endAngle;
  });

  const legend = rows.map((row, index) => `
    <div class="crime-tooltip-neighborhood-row">
      <span class="crime-tooltip-neighborhood-swatch" style="background:${NEIGHBORHOOD_PALETTE[index % NEIGHBORHOOD_PALETTE.length]}"></span>
      <span class="crime-tooltip-neighborhood-name">${escapeTooltipText(row.name)}</span>
      <span class="crime-tooltip-neighborhood-value">${numberFormatter.format(row.total)}</span>
    </div>
  `).join('');

  return `
    <div class="crime-tooltip-breakdown">
      <svg class="crime-tooltip-donut" viewBox="0 0 84 84" role="img" aria-label="Ocorrências por bairro">
        ${paths.join('')}
      </svg>
      <div class="crime-tooltip-neighborhoods">${legend}</div>
    </div>
  `;
}

/** Rich HTML content for territory tooltips, styled via the `.crime-tooltip` CSS class. */
function buildTooltipHtml(title, total, intensity, percentage, homicideRate, neighborhoodRows = []) {
  const level = getRiskLevel(intensity);
  const occurrenceWord = total === 1 ? 'ocorrência' : 'ocorrências';
  const percentageHtml =
    percentage != null
      ? `<div class="crime-tooltip-percentage">${decimalFormatter.format(percentage)}% dos crimes filtrados</div>`
      : '';
  const homicideHtml =
    homicideRate != null
      ? `<div class="crime-tooltip-homicide">Taxa de homicídios: ${decimalFormatter.format(homicideRate)} / 100 mil hab.</div>`
      : '';
  const breakdownHtml = neighborhoodRows.length ? buildNeighborhoodDonut(neighborhoodRows) : '';
  return `
    <div class="crime-tooltip-title">${escapeTooltipText(title)}</div>
    ${breakdownHtml}
    <div class="crime-tooltip-row">
      <span class="crime-tooltip-dot" style="background:${level.color}"></span>
      <span class="crime-tooltip-level">${level.label}</span>
    </div>
    <div class="crime-tooltip-total">${numberFormatter.format(total)} ${occurrenceWord}</div>
    ${percentageHtml}
    ${homicideHtml}
  `;
}

/** Collects [lat, lng] pairs from a GeoJSON geometry's coordinate tree. */
function collectPoints(geometry) {
  const pts = [];
  const walk = (value) => {
    if (!Array.isArray(value)) return;
    if (value.length >= 2 && typeof value[0] === 'number' && typeof value[1] === 'number') {
      pts.push([value[1], value[0]]); // GeoJSON [lng, lat] → [lat, lng]
      return;
    }
    value.forEach(walk);
  };
  walk(geometry?.coordinates);
  return pts;
}

function featureCentroid(feature) {
  const pts = collectPoints(feature?.geometry);
  if (!pts.length) return null;
  const lats = pts.map((p) => p[0]);
  const lngs = pts.map((p) => p[1]);
  return [
    (Math.min(...lats) + Math.max(...lats)) / 2,
    (Math.min(...lngs) + Math.max(...lngs)) / 2,
  ];
}

/** Bounding box (Leaflet LatLngBounds) covering every feature's coordinates. */
function boundsFromFeatures(features) {
  let south = Infinity, west = Infinity, north = -Infinity, east = -Infinity;
  features.forEach((feature) => {
    collectPoints(feature.geometry).forEach(([lat, lng]) => {
      if (lat < south) south = lat;
      if (lat > north) north = lat;
      if (lng < west) west = lng;
      if (lng > east) east = lng;
    });
  });
  if (!Number.isFinite(south)) return null;
  return L.latLngBounds([south, west], [north, east]);
}

// ─── Sub-components ───────────────────────────────────────────────────────────

/** Syncs the React zoom state with the Leaflet map. */
function ZoomWatcher({ onChange }) {
  const map = useMap();
  useEffect(() => { onChange(map.getZoom()); }, [map, onChange]);
  useMapEvents({ zoomend: (e) => onChange(e.target.getZoom()) });
  return null;
}

function BaseLayerWatcher({ onChange }) {
  useMapEvents({
    baselayerchange: (event) => onChange(event.name),
  });
  return null;
}

/** Reports which municipality (if any) currently sits under the map's center. */
function CityWatcher({ municipalityFeatures, onChange }) {
  const map = useMap();

  const detect = useCallback(() => {
    const center = map.getCenter();
    const pt = turfPoint([center.lng, center.lat]);
    const match = municipalityFeatures.find((feature) => {
      try {
        return booleanPointInPolygon(pt, feature);
      } catch {
        return false;
      }
    });
    onChange(match?.properties?.ibge_id ?? null);
  }, [map, municipalityFeatures, onChange]);

  useEffect(() => {
    detect();
    map.on('moveend zoomend', detect);
    return () => map.off('moveend zoomend', detect);
  }, [map, detect]);

  return null;
}

/** Locks the map to the region: fits it once, then forbids zooming/panning outside. */
function RegionLock({ bounds }) {
  const map = useMap();

  useEffect(() => {
    if (!bounds) return;
    map.fitBounds(bounds, { padding: [16, 16] });
    map.setMinZoom(map.getZoom());
    map.setMaxBounds(bounds.pad(0.05));
  }, [map, bounds]);

  return null;
}

/**
 * When a municipality is selected (via filter or click), restricts panning to its
 * bounds and zooms in so only its neighborhoods are visible. Deselecting only lifts
 * the pan restriction — it never forces the view to move.
 */
function FocusMunicipality({ features, cityId, regionBounds }) {
  const map = useMap();
  const wasFocused = useRef(false);

  useEffect(() => {
    if (cityId != null) {
      const cityFeatures = features.filter((f) => f.properties.ibge_id === cityId);
      const bounds = boundsFromFeatures(cityFeatures);
      if (!bounds) return;
      map.setMaxBounds(bounds.pad(0.15));
      map.fitBounds(bounds, { padding: [24, 24] });
      wasFocused.current = true;
    } else if (wasFocused.current && regionBounds) {
      map.setMaxBounds(regionBounds.pad(0.05));
      wasFocused.current = false;
    }
  }, [map, features, cityId, regionBounds]);

  return null;
}

/** Renders the crime heat map from pre-computed centroid points. */
function HeatLayer({ points }) {
  const map = useMap();

  useEffect(() => {
    if (!points.length) return;
    // leaflet.heat expects [lat, lng, intensity] — center is already [lat, lng]
    const heat = L.heatLayer(
      points.map(({ center, intensity }) => [center[0], center[1], intensity]),
      {
        radius: 30,
        blur: 22,
        maxZoom: 16,
        gradient: {
          0.20: '#ffcdd2',
          0.40: '#ef9a9a',
          0.60: '#e53935',
          0.80: '#b71c1c',
          1.00: '#7f0000',
        },
      }
    ).addTo(map);
    return () => heat.remove();
  }, [map, points]);

  return null;
}

/**
 * Territory polygons (municipalities or neighborhoods) colored by crime intensity.
 * Rebuilt imperatively to avoid React-Leaflet GeoJSON re-render flicker.
 */
function TerritoryBoundaries({ features, getIntensity, getLabel, onFeatureClick }) {
  const map = useMap();
  const layerRef = useRef(null);

  useEffect(() => {
    if (layerRef.current) {
      map.removeLayer(layerRef.current);
      layerRef.current = null;
    }
    if (!features?.length) return undefined;

    layerRef.current = L.geoJSON(
      { type: 'FeatureCollection', features },
      {
        style: (feature) => ({
          fillColor: getRiskColor(getIntensity(feature)),
          color: '#1a3050',
          weight: 0.8,
          opacity: 0.85,
          fillOpacity: 0.55,
        }),
        onEachFeature: (feature, layer) => {
          let scrollFrame = null;
          let scrollDirection = 1;
          let lastFrameTime = 0;
          let pauseUntil = 0;
          let neighborhoodList = null;

          const stopNeighborhoodScroll = () => {
            if (scrollFrame != null) cancelAnimationFrame(scrollFrame);
            scrollFrame = null;
            neighborhoodList = null;
            lastFrameTime = 0;
            pauseUntil = 0;
          };

          const animateNeighborhoodScroll = (timestamp) => {
            if (!neighborhoodList?.isConnected) {
              stopNeighborhoodScroll();
              return;
            }
            const maxScroll = neighborhoodList.scrollHeight - neighborhoodList.clientHeight;
            if (maxScroll <= 0) {
              scrollFrame = null;
              return;
            }
            if (timestamp < pauseUntil) {
              scrollFrame = requestAnimationFrame(animateNeighborhoodScroll);
              return;
            }
            const elapsed = lastFrameTime ? Math.min((timestamp - lastFrameTime) / 1000, 0.05) : 0;
            lastFrameTime = timestamp;
            neighborhoodList.scrollTop += scrollDirection * elapsed * 18;

            if (scrollDirection > 0 && neighborhoodList.scrollTop >= maxScroll) {
              neighborhoodList.scrollTop = maxScroll;
              scrollDirection = -1;
              pauseUntil = timestamp + 1200;
            } else if (scrollDirection < 0 && neighborhoodList.scrollTop <= 0) {
              neighborhoodList.scrollTop = 0;
              scrollDirection = 1;
              pauseUntil = timestamp + 1200;
            }
            scrollFrame = requestAnimationFrame(animateNeighborhoodScroll);
          };

          const startNeighborhoodScroll = () => {
            const tooltipElement = layer.getTooltip()?.getElement();
            const list = tooltipElement?.querySelector('.crime-tooltip-neighborhoods');
            if (list && list === neighborhoodList && scrollFrame != null) return;
            stopNeighborhoodScroll();
            neighborhoodList = list ?? null;
            if (!neighborhoodList || neighborhoodList.scrollHeight <= neighborhoodList.clientHeight) return;
            scrollDirection = 1;
            scrollFrame = requestAnimationFrame(animateNeighborhoodScroll);
          };

          layer.bindTooltip(getLabel(feature), {
            sticky: true,
            direction: 'top',
            opacity: 1,
            className: 'crime-tooltip',
          });
          layer.on('tooltipopen', startNeighborhoodScroll);
          layer.on('tooltipclose', stopNeighborhoodScroll);
          layer.on('mouseover', startNeighborhoodScroll);
          layer.on('click', () => {
            onFeatureClick?.(feature);
            // Zoom-on-click is reserved for bairros; município selection is handled by FocusMunicipality.
            const isNeighborhood = feature.properties.neighborhood_name != null;
            if (!isNeighborhood) return;
            const related = features.filter(
              (f) =>
                f.properties.ibge_id === feature.properties.ibge_id &&
                normalizeName(f.properties.neighborhood_name) === normalizeName(feature.properties.neighborhood_name)
            );
            const bounds = boundsFromFeatures(related);
            if (bounds) map.fitBounds(bounds, { padding: [40, 40] });
          });
        },
      }
    ).addTo(map);

    return () => {
      if (layerRef.current) {
        layerRef.current.eachLayer((layer) => {
          layer.closeTooltip();
          layer.off('tooltipclose');
        });
        map.removeLayer(layerRef.current);
      }
    };
  }, [map, features, getIntensity, getLabel, onFeatureClick]);

  return null;
}

/**
 * Dims the whole map except the selected territory, which is left clear and
 * outlined — computed with turf.mask so ring winding/topology can't leave gaps.
 */
function SelectionHighlight({ selectedFeatures }) {
  const map = useMap();
  const layerRef = useRef(null);

  useEffect(() => {
    if (layerRef.current) {
      map.removeLayer(layerRef.current);
      layerRef.current = null;
    }
    if (!selectedFeatures?.length) return undefined;

    const group = L.layerGroup();

    const masked = turfMask({ type: 'FeatureCollection', features: selectedFeatures });
    L.geoJSON(masked, {
      style: { stroke: false, fillColor: '#03060b', fillOpacity: 0.72, interactive: false },
    }).addTo(group);

    L.geoJSON(
      { type: 'FeatureCollection', features: selectedFeatures },
      { style: { color: '#ffffff', weight: 3, fillOpacity: 0, interactive: false } }
    ).addTo(group);

    layerRef.current = group.addTo(map);

    return () => {
      if (layerRef.current) map.removeLayer(layerRef.current);
    };
  }, [map, selectedFeatures]);

  return null;
}

// ─── Main component ───────────────────────────────────────────────────────────

function HeatMapView({
  filters = {},
  activeFilterLabels = [],
  selectedBaseLayer = 'Mapa Claro',
  onBaseLayerChange,
  onSelectMunicipality,
  onSelectNeighborhood,
}) {
  const [municipalitiesGeo, setMunicipalitiesGeo] = useState(null);
  const [neighborhoodsGeo, setNeighborhoodsGeo]    = useState(null);
  const [loading, setLoading]                      = useState(true);
  const [zoom, setZoom]                            = useState(10);
  const [currentCityId, setCurrentCityId]          = useState(null);
  const [cityStatistics, setCityStatistics]        = useState(EMPTY_STATISTICS);
  const [neighborhoodStatistics, setNeighborhoodStatistics] = useState(EMPTY_STATISTICS);
  const [neighborhoodStatisticsByCity, setNeighborhoodStatisticsByCity] = useState({});
  const [cityNeighborhoodDirectory, setCityNeighborhoodDirectory] = useState([]);

  const activeBaseLayer = BASE_LAYER_NAMES.includes(selectedBaseLayer) ? selectedBaseLayer : BASE_LAYER_NAMES[0];

  // Load the Baixada Santista boundary layers once; the browser caches them afterwards.
  useEffect(() => {
    Promise.all([
      fetch(MUNICIPALITIES_GEOJSON_URL).then((r) => r.json()),
      fetch(NEIGHBORHOODS_GEOJSON_URL).then((r) => r.json()),
    ])
      .then(([municipalities, neighborhoods]) => {
        setMunicipalitiesGeo(municipalities);
        setNeighborhoodsGeo(neighborhoods);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const municipalityFeatures = municipalitiesGeo?.features ?? [];
  const neighborhoodFeatures = neighborhoodsGeo?.features ?? [];

  const cityIds = useMemo(
    () => [...new Set(municipalityFeatures.map((f) => f.properties.ibge_id))],
    [municipalityFeatures]
  );

  const regionBounds = useMemo(() => boundsFromFeatures(municipalityFeatures), [municipalityFeatures]);

  // A single-municipality filter (from the filter bar or a map click) takes priority over
  // whatever city happens to be under the map's center, so the focused city's data doesn't
  // get diluted by the rest of the region once the user filters/selects it.
  const selectedMunicipalityId = filters.municipalityIds?.length === 1 ? Number(filters.municipalityIds[0]) : null;
  const effectiveCityId = selectedMunicipalityId ?? currentCityId;

  // City-level (município) crime counts for the whole region — drives the map at low zoom.
  useEffect(() => {
    if (!cityIds.length) return undefined;
    let cancelled = false;
    fetchCrimeStatistics({ ...filters, municipalityIds: cityIds.map(String), neighborhoodIds: [] })
      .then((data) => { if (!cancelled) setCityStatistics(data); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [filters, cityIds]);

  useEffect(() => {
    if (!cityIds.length) return undefined;
    let cancelled = false;
    setNeighborhoodStatisticsByCity({});
    Promise.all(cityIds.map(async (ibgeId) => {
      try {
        const result = await fetchCrimeStatistics({
          ...filters,
          municipalityIds: [String(ibgeId)],
          neighborhoodIds: [],
        });
        return [ibgeId, result.by_location ?? []];
      } catch {
        return [ibgeId, []];
      }
    })).then((results) => {
      if (!cancelled) setNeighborhoodStatisticsByCity(Object.fromEntries(results));
    });
    return () => { cancelled = true; };
  }, [filters, cityIds]);

  // Neighborhood-level (bairro) crime counts for the focused city — drives high zoom.
  useEffect(() => {
    if (!effectiveCityId) { setNeighborhoodStatistics(EMPTY_STATISTICS); return undefined; }
    let cancelled = false;
    fetchCrimeStatistics({ ...filters, municipalityIds: [String(effectiveCityId)], neighborhoodIds: [] })
      .then((data) => { if (!cancelled) setNeighborhoodStatistics(data); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [filters, effectiveCityId]);

  // Authoritative id ↔ name directory for the focused city's bairros (drives click-to-filter).
  useEffect(() => {
    if (!effectiveCityId) { setCityNeighborhoodDirectory([]); return undefined; }
    let cancelled = false;
    fetchNeighborhoods(effectiveCityId)
      .then((rows) => { if (!cancelled) setCityNeighborhoodDirectory(rows); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [effectiveCityId]);

  const cityStatsById = useMemo(
    () => new Map(cityStatistics.by_location.map((row) => [row.id, row])),
    [cityStatistics]
  );
  const cityTotals = useMemo(
    () => new Map([...cityStatsById.entries()].map(([id, row]) => [id, row.total])),
    [cityStatsById]
  );
  const cityMax = useMemo(() => Math.max(1, ...cityTotals.values(), 0), [cityTotals]);

  const neighborhoodStatsByName = useMemo(
    () => new Map(neighborhoodStatistics.by_location.map((row) => [normalizeName(row.name), row])),
    [neighborhoodStatistics]
  );
  const neighborhoodRowsByCity = useMemo(() => {
    const rows = new Map();
    for (const ibgeId of cityIds) {
      const cityFeatures = neighborhoodFeatures.filter((feature) => feature.properties.ibge_id === ibgeId);
      const totalsByName = new Map(
        (neighborhoodStatisticsByCity[ibgeId] ?? []).map((row) => [normalizeName(row.name), row.total])
      );
      const uniqueNames = new Map();
      cityFeatures.forEach((feature) => {
        const name = feature.properties.neighborhood_name;
        const normalizedName = normalizeName(name);
        if (!uniqueNames.has(normalizedName)) uniqueNames.set(normalizedName, name);
      });
      rows.set(ibgeId, [...uniqueNames.entries()]
        .map(([normalizedName, name]) => ({ name, total: totalsByName.get(normalizedName) ?? 0 }))
        .filter((row) => row.total > 0)
        .sort((first, second) => second.total - first.total));
    }
    return rows;
  }, [cityIds, neighborhoodFeatures, neighborhoodStatisticsByCity]);
  const neighborhoodTotals = useMemo(
    () => new Map([...neighborhoodStatsByName.entries()].map(([name, row]) => [name, row.total])),
    [neighborhoodStatsByName]
  );
  const neighborhoodMax = useMemo(() => Math.max(1, ...neighborhoodTotals.values(), 0), [neighborhoodTotals]);

  const showNeighborhoods = effectiveCityId != null && zoom >= NEIGHBORHOOD_ZOOM;

  const visibleNeighborhoods = useMemo(
    () => (showNeighborhoods ? neighborhoodFeatures.filter((f) => f.properties.ibge_id === effectiveCityId) : []),
    [showNeighborhoods, neighborhoodFeatures, effectiveCityId]
  );

  const getMunicipalityIntensity = useCallback(
    (feature) => (cityTotals.get(feature.properties.ibge_id) ?? 0) / cityMax,
    [cityTotals, cityMax]
  );
  const getNeighborhoodIntensity = useCallback(
    (feature) => (neighborhoodTotals.get(normalizeName(feature.properties.neighborhood_name)) ?? 0) / neighborhoodMax,
    [neighborhoodTotals, neighborhoodMax]
  );

  const getMunicipalityLabel = useCallback(
    (feature) => {
      const row = cityStatsById.get(feature.properties.ibge_id);
      const total = row?.total ?? 0;
      return buildTooltipHtml(
        feature.properties.municipality_name,
        total,
        cityMax ? total / cityMax : null,
        row?.percentage ?? null,
        row?.homicide_rate_per_100k ?? null,
        neighborhoodRowsByCity.get(feature.properties.ibge_id) ?? []
      );
    },
    [cityStatsById, cityMax, neighborhoodRowsByCity]
  );
  const getNeighborhoodLabel = useCallback(
    (feature) => {
      const row = neighborhoodStatsByName.get(normalizeName(feature.properties.neighborhood_name));
      const total = row?.total ?? 0;
      return buildTooltipHtml(
        feature.properties.neighborhood_name,
        total,
        neighborhoodMax ? total / neighborhoodMax : null,
        row?.percentage ?? null,
        row?.homicide_rate_per_100k ?? null
      );
    },
    [neighborhoodStatsByName, neighborhoodMax]
  );

  const heatPoints = useMemo(() => {
    if (showNeighborhoods) {
      return visibleNeighborhoods
        .map((f) => ({ center: featureCentroid(f), intensity: getNeighborhoodIntensity(f) }))
        .filter((p) => p.center);
    }
    return municipalityFeatures
      .map((f) => ({ center: featureCentroid(f), intensity: getMunicipalityIntensity(f) }))
      .filter((p) => p.center);
  }, [showNeighborhoods, visibleNeighborhoods, municipalityFeatures, getNeighborhoodIntensity, getMunicipalityIntensity]);

  const handleZoom = useCallback((z) => setZoom(z), []);

  // ── Click-to-filter selection ──
  const selectedNeighborhoodId = filters.neighborhoodIds?.length === 1 ? Number(filters.neighborhoodIds[0]) : null;

  const selectedMunicipalityFeatures = useMemo(
    () => municipalityFeatures.filter((f) => f.properties.ibge_id === selectedMunicipalityId),
    [municipalityFeatures, selectedMunicipalityId]
  );

  const selectedNeighborhoodName = useMemo(
    () => cityNeighborhoodDirectory.find((n) => Number(n.id) === selectedNeighborhoodId)?.neighborhood_name,
    [cityNeighborhoodDirectory, selectedNeighborhoodId]
  );
  const selectedNeighborhoodFeatures = useMemo(
    () =>
      selectedNeighborhoodName
        ? visibleNeighborhoods.filter((f) => normalizeName(f.properties.neighborhood_name) === normalizeName(selectedNeighborhoodName))
        : [],
    [visibleNeighborhoods, selectedNeighborhoodName]
  );

  const handleMunicipalityClick = useCallback(
    (feature) => {
      const ibgeId = feature.properties.ibge_id;
      onSelectMunicipality?.(selectedMunicipalityId === ibgeId ? null : ibgeId);
    },
    [selectedMunicipalityId, onSelectMunicipality]
  );
  const handleNeighborhoodClick = useCallback(
    (feature) => {
      const match = cityNeighborhoodDirectory.find(
        (n) => normalizeName(n.neighborhood_name) === normalizeName(feature.properties.neighborhood_name)
      );
      if (!match) return;
      if (selectedNeighborhoodId === Number(match.id)) {
        onSelectNeighborhood?.(null);
      } else {
        onSelectNeighborhood?.({ ibgeId: feature.properties.ibge_id, neighborhoodId: match.id });
      }
    },
    [cityNeighborhoodDirectory, selectedNeighborhoodId, onSelectNeighborhood]
  );

  return (
    <div className="map-wrapper">
      {/* ── Legend ── */}
      <div className="legend" aria-label="Legenda de intensidade">
        <span className="legend-title">Níveis de risco</span>
        <div className="legend-items">
          <span className="legend-color-bar" aria-hidden="true" />
          <div className="legend-labels">
            <span>Muito baixo</span>
            <span>Baixo</span>
            <span>Médio</span>
            <span>Alto</span>
            <span>Muito alto</span>
          </div>
        </div>
      </div>

      {activeFilterLabels.length > 0 && (
        <div className="active-filters-badge" aria-label="Filtros ativos">
          {activeFilterLabels.join(' · ')}
        </div>
      )}

      {loading && (
        <div className="map-loading-overlay">
          Carregando mapa da Baixada Santista…
        </div>
      )}

      {!loading && !showNeighborhoods && (
        <div className="zoom-hint">
          Aproxime o mapa para ver os bairros de cada cidade
        </div>
      )}

      {!loading && regionBounds && (
        <MapContainer
          minZoom={7}
          maxZoom={17}
          maxBoundsViscosity={1.0}
          scrollWheelZoom
          className="map-view"
        >
          <LayersControl position="topright">
            <BaseLayer checked={activeBaseLayer === 'Mapa Claro'} name="Mapa Claro">
              <TileLayer
                attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              />
            </BaseLayer>
            <BaseLayer checked={activeBaseLayer === 'Mapa Escuro'} name="Mapa Escuro">
              <TileLayer
                attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>'
                url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
                subdomains="abcd"
                maxZoom={20}
              />
            </BaseLayer>
            <BaseLayer checked={activeBaseLayer === 'Satélite'} name="Satélite">
              <TileLayer
                attribution='Tiles &copy; Esri'
                url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
              />
            </BaseLayer>
          </LayersControl>

          <BaseLayerWatcher onChange={onBaseLayerChange} />

          <RegionLock bounds={regionBounds} />
          <FocusMunicipality
            features={municipalityFeatures}
            cityId={selectedMunicipalityId}
            regionBounds={regionBounds}
          />
          <ZoomWatcher onChange={handleZoom} />
          <CityWatcher municipalityFeatures={municipalityFeatures} onChange={setCurrentCityId} />

          {heatPoints.length > 0 && <HeatLayer points={heatPoints} />}

          {showNeighborhoods ? (
            <TerritoryBoundaries
              features={visibleNeighborhoods}
              getIntensity={getNeighborhoodIntensity}
              getLabel={getNeighborhoodLabel}
              onFeatureClick={handleNeighborhoodClick}
            />
          ) : (
            <TerritoryBoundaries
              features={municipalityFeatures}
              getIntensity={getMunicipalityIntensity}
              getLabel={getMunicipalityLabel}
              onFeatureClick={handleMunicipalityClick}
            />
          )}

          <SelectionHighlight
            selectedFeatures={showNeighborhoods ? selectedNeighborhoodFeatures : selectedMunicipalityFeatures}
          />
        </MapContainer>
      )}
    </div>
  );
}

export default HeatMapView;
