import { MapContainer, TileLayer, LayersControl, useMap, useMapEvents } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet.heat';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

/** Pre-processed boundary GeoJSON generated by scripts/process-geo.mjs */
const GEOJSON_URL = '/br-municipalities.geojson';

/** Zoom level at which municipality polygon boundaries appear */
const BOUNDARY_ZOOM = 7;

const { BaseLayer } = LayersControl;

function getRiskLevel(intensity) {
  if (intensity == null)    return { label: 'Sem dados',  color: '#9aa4b2' };
  if (intensity >= 0.8)     return { label: 'Muito alto', color: '#d7263d' };
  if (intensity >= 0.6)     return { label: 'Alto',       color: '#ff6b35' };
  if (intensity >= 0.4)     return { label: 'Médio',      color: '#f4b942' };
  if (intensity >= 0.2)     return { label: 'Baixo',      color: '#7ed957' };
  return                           { label: 'Muito baixo',color: '#2ec4b6' };
}

function getRiskColor(intensity) {
  return getRiskLevel(intensity).color;
}

/** Collects [lat, lng] pairs from a GeoJSON geometry's coordinate tree. */
function collectPoints(geometry) {
  const pts = [];
  const walk = (value) => {
    if (!Array.isArray(value)) return;
    if (value.length >= 2 && typeof value[0] === 'number' && typeof value[1] === 'number') {
      pts.push([value[1], value[0]]); // GeoJSON [lng, lat] → [lat, lng]
      return;
    }
    value.forEach(walk);
  };
  walk(geometry?.coordinates);
  return pts;
}

function featureCentroid(feature) {
  const pts = collectPoints(feature?.geometry);
  if (!pts.length) return null;
  const lats = pts.map((p) => p[0]);
  const lngs = pts.map((p) => p[1]);
  return [
    (Math.min(...lats) + Math.max(...lats)) / 2,
    (Math.min(...lngs) + Math.max(...lngs)) / 2,
  ];
}

function overlapsViewport(feature, bounds) {
  const pts = collectPoints(feature?.geometry);
  if (!pts.length) return false;
  const lats = pts.map((p) => p[0]);
  const lngs = pts.map((p) => p[1]);
  return !(
    Math.max(...lngs) < bounds.getWest()  ||
    Math.min(...lngs) > bounds.getEast()  ||
    Math.max(...lats) < bounds.getSouth() ||
    Math.min(...lats) > bounds.getNorth()
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

/** Syncs the React zoom state with the Leaflet map. */
function ZoomWatcher({ onChange }) {
  const map = useMap();
  useEffect(() => { onChange(map.getZoom()); }, [map, onChange]);
  useMapEvents({ zoomend: (e) => onChange(e.target.getZoom()) });
  return null;
}

/** Renders the crime heat map from pre-computed centroid points. */
function HeatLayer({ points }) {
  const map = useMap();

  useEffect(() => {
    if (!points.length) return;
    // leaflet.heat expects [lat, lng, intensity] — center is already [lat, lng]
    const heat = L.heatLayer(
      points.map(({ center, intensity }) => [center[0], center[1], intensity]),
      {
        radius: 30,
        blur: 22,
        maxZoom: 10,
        gradient: {
          0.15: '#2ec4b6',
          0.40: '#7ed957',
          0.65: '#f4b942',
          0.82: '#ff6b35',
          1.00: '#d7263d',
        },
      }
    ).addTo(map);
    return () => heat.remove();
  }, [map, points]);

  return null;
}

/**
 * Municipality boundary polygons for the visible viewport.
 * Rebuilt imperatively whenever the map moves or zooms to avoid
 * React-Leaflet GeoJSON re-render flicker.
 */
function MunicipalityBoundaries({ data }) {
  const map = useMap();
  const layerRef = useRef(null);

  const rebuild = useCallback(() => {
    if (layerRef.current) {
      map.removeLayer(layerRef.current);
      layerRef.current = null;
    }
    if (!data?.features) return;

    const bounds = map.getBounds();
    const visible = data.features.filter((f) => overlapsViewport(f, bounds));

    layerRef.current = L.geoJSON(
      { type: 'FeatureCollection', features: visible },
      {
        style: (feature) => ({
          fillColor: getRiskColor(feature?.properties?.intensity ?? null),
          color: '#1a3050',
          weight: 0.8,
          opacity: 0.85,
          fillOpacity: 0.55,
        }),
        onEachFeature: (feature, layer) => {
          const intensity = feature?.properties?.intensity ?? null;
          const level = getRiskLevel(intensity);
          const pct = intensity == null ? 'Sem dados' : `${Math.round(intensity * 100)}%`;
          layer.bindTooltip(
            `<strong>${level.label}</strong><br/>Intensidade: ${pct}`,
            { sticky: true }
          );
        },
      }
    ).addTo(map);
  }, [map, data]);

  useEffect(() => {
    rebuild();
    map.on('moveend zoomend', rebuild);
    return () => {
      map.off('moveend zoomend', rebuild);
      if (layerRef.current) map.removeLayer(layerRef.current);
    };
  }, [map, rebuild]);

  return null;
}

// ─── Main component ───────────────────────────────────────────────────────────

function HeatMapView() {
  const [geojsonData, setGeojsonData] = useState(null);
  const [loading, setLoading]         = useState(true);
  const [zoom, setZoom]               = useState(4);

  // Load the full municipality GeoJSON once; browser caches it afterwards.
  useEffect(() => {
    fetch(GEOJSON_URL)
      .then((r) => r.json())
      .then((data) => { setGeojsonData(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  // Centroid points drive the heat map layer across all of Brazil.
  const heatPoints = useMemo(() => {
    if (!geojsonData?.features) return [];
    return geojsonData.features
      .map((f) => ({ center: featureCentroid(f), intensity: f.properties?.intensity ?? null }))
      .filter((p) => p.center && p.intensity != null);
  }, [geojsonData]);

  const handleZoom  = useCallback((z) => setZoom(z), []);
  const showBounds  = zoom >= BOUNDARY_ZOOM;

  return (
    <div className="map-wrapper">
      {/* ── Legend ── */}
      <div className="legend" aria-label="Legenda de intensidade">
        <span className="legend-title">Nível de risco</span>
        <div className="legend-scale">
          <span className="legend-color very-low"  />
          <span className="legend-color low"        />
          <span className="legend-color medium"     />
          <span className="legend-color high"       />
          <span className="legend-color very-high"  />
          <span className="legend-color no-data"    />
        </div>
        <div className="legend-labels">
          <span>Muito baixo</span>
          <span>Baixo</span>
          <span>Médio</span>
          <span>Alto</span>
          <span>Muito alto</span>
          <span>Sem dados</span>
        </div>
      </div>

      {loading && (
        <div className="map-loading-overlay">
          Carregando 5.572 municípios brasileiros…
        </div>
      )}

      {!loading && !showBounds && (
        <div className="zoom-hint">
          Aproxime o mapa para ver as demarcações municipais
        </div>
      )}

      <MapContainer
        center={[-14.235, -51.9253]}
        zoom={4}
        minZoom={3}
        maxZoom={14}
        scrollWheelZoom
        className="map-view"
      >
        <LayersControl position="topright">
          <BaseLayer checked name="Mapa Claro">
            <TileLayer
              attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
          </BaseLayer>
          <BaseLayer name="Satélite">
            <TileLayer
              attribution='Tiles &copy; Esri'
              url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
            />
          </BaseLayer>
        </LayersControl>

        <ZoomWatcher onChange={handleZoom} />

        {/* Heat map visible at all zoom levels once data loads */}
        {heatPoints.length > 0 && <HeatLayer points={heatPoints} />}

        {/* Municipality boundaries appear when zoom >= BOUNDARY_ZOOM */}
        {showBounds && geojsonData && <MunicipalityBoundaries data={geojsonData} />}
      </MapContainer>
    </div>
  );
}

export default HeatMapView;
